---
swagger: "2.0"
info:
  description: "Yet Another Geo Agregator API"
  version: "1.0.0"
  title: "Yet Another Geo Agregator API"
host: "127.0.0.1:8080"
basePath: "/v1"
schemes:
- "https"
produces:
- "application/json"
paths:
  /squares:
    get:
      tags:
      - "Squares"
      summary: "Get detailed squares"
      description: "The minute by minute detail of people in the given area between\
        \ the initial instant and the final instant required"
      operationId: "squares_get"
      parameters:
      - name: "lat_max"
        in: "query"
        description: "Latitude of the NO point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lat_min"
        in: "query"
        description: "Longitude of the South East point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lon_max"
        in: "query"
        description: "Latitude of the South East point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lon_min"
        in: "query"
        description: "Longitude of the NO point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "start"
        in: "query"
        description: "The beginning of the interval considered for the details required."
        required: true
        type: "number"
        format: "double"
      - name: "end"
        in: "query"
        description: "The end of the interval considered for the details required."
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "An array of products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Square"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.squares_controller"
    post:
      tags:
      - "Squares"
      summary: "Create squares"
      description: "Create new squares."
      operationId: "squares_post"
      parameters:
      - name: "timestamp"
        in: "query"
        description: "Timestamp to which the counts were made."
        required: true
        type: "integer"
        format: "int32"
      - in: "body"
        name: "zones"
        description: "Array of zones and associated counts."
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Zone"
      responses:
        200:
          description: "OK"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.squares_controller"
  /squares/average:
    get:
      tags:
      - "Squares"
      summary: "Average"
      description: "The average of people in the given area between the initial instant\
        \ and the final instant required"
      operationId: "squares_average_get"
      parameters:
      - name: "lat_max"
        in: "query"
        description: "Latitude of the NO point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lat_min"
        in: "query"
        description: "Longitude of the South East point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lon_max"
        in: "query"
        description: "Latitude of the South East point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "lon_min"
        in: "query"
        description: "Longitude of the NO point describing the zone."
        required: true
        type: "number"
        format: "double"
      - name: "start"
        in: "query"
        description: "The beginning of the interval considered for the average required."
        required: true
        type: "number"
        format: "double"
      - name: "end"
        in: "query"
        description: "The end of the interval considered for the average required."
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "An array of products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Square"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.squares_controller"
  /squares/streaming:
    get:
      summary: "Most recent counts."
      description: "Returns the most recent counts."
      operationId: "squares_streaming_get"
      parameters: []
      responses:
        200:
          description: "X"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Square:
    type: "object"
    properties:
      lat_max:
        type: "number"
        format: "double"
        description: "Latitude of the NO corner of the square."
      lon_min:
        type: "number"
        format: "double"
        description: "Longitude of the NO corner of the square."
      count:
        type: "integer"
        format: "int32"
        description: "Total number of phone localized in the square."
      start:
        type: "string"
        description: "Date time in this format '2002-12-25 00:00:00' to which the\
          \ count was made or the average begins."
      end:
        type: "string"
        description: "Date time in this format '2002-12-25 00:00:00' to which the\
          \ count was made or the average ends."
  Zone:
    type: "object"
    properties:
      lat_max:
        type: "number"
        format: "double"
        description: "Latitude of the NO corner of the square."
      lon_min:
        type: "number"
        format: "double"
        description: "Longitude of the NO corner of the square."
      count:
        type: "integer"
        format: "int32"
        description: "Total number of phone localized in the square."
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
